config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: "users/registrations"
  }
  devise_scope :user do
    get'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
    get '/users/sign_out', to: 'devise/sessions#destroy'
  end
  

  resources :users, only: :show do
    collection do
      get 'edit_profile', 'edit_address'
      get 'sell_items'
      get 'bought_items'
      patch 'update_profile', 'update_address'
      get 'favorite_items'
    end
  end
 
  root 'items#index'

  resources :payment_cards, only: [:new, :create, :index, :destroy]
  resources :items do
    resources :favorites, only: [:create, :destroy]
    collection do
      get 'search'
    end
    resources :purchases do
      collection do
        get :buy
        post :pay
      end
    end
  end
  resources :categories, only: [:index, :show] do
    collection do
      get "children_category"
      get "grandchildren_category"
    end
  end
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :item
  belongs_to :user
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :set_item, only: [:create, :destroy]
  
  def create
    @favorite = current_user.favorites.create(favorite_params)
    respond_to do |format|
      format.html { redirect_to @item }
      format.js
    end
  end

  def destroy
    @favorite = Favorite.find_by(favorite_params, user_id: current_user.id)
    @favorite.destroy
    respond_to do |format|
      format.html { redirect_to @item }
      format.js
    end
  end

  private
  def set_item
    @item = Item.find(params[:item_id])
  end
  def favorite_params
    params.permit(:item_id)
  end


end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/favorites/_favorite.html.haml
- if  current_user.favorites.find_by(item_id: @item.id)
  #favorited
    = link_to item_favorite_path(@item, current_user.favorites.find_by(item_id: @item.id)), method: :delete, remote: true do
      = image_tag "icon/icon_stared.png", size:'25x25'
      = "いいね!   #{@item.favorites.count}"
- else
  #favorite
    = link_to item_favorites_path(@item, current_user.favorites.build), method: :post, remote: true do
      = image_tag "icon/icon_star.png", size: '25x25'
      = "いいね!   #{@item.favorites.count}"

app/views/favorites/create.js.erb
$("#favorite").html("<%= escape_javascript(render('favorites/favorite')) %>");

app/views/favorites/destroy.js.erb
$("#favorited").html("<%= escape_javascript(render('favorites/favorite')) %>");