config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: "users/registrations"
  }
  devise_scope :user do
    get'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
    get '/users/sign_out', to: 'devise/sessions#destroy'
  end
  

  resources :users, only: :show do
    collection do
      get 'edit_profile', 'edit_address'
      get 'sell_items'
      get 'bought_items'
      patch 'update_profile', 'update_address'
      get 'favorite_items'
    end
  end
 
  root 'items#index'

  resources :payment_cards, only: [:new, :create, :index, :destroy]
  resources :items do
    resources :favorites, only: [:create, :destroy]
    collection do
      get 'search'
    end
    resources :purchases do
      collection do
        get :buy
        post :pay
      end
    end
  end
  resources :categories, only: [:index, :show] do
    collection do
      get "children_category"
      get "grandchildren_category"
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  validates :name, presence: true
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:google_oauth2]


  has_many :sns_credentials, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorite_items, through: :favorites, source: :item, dependent: :destroy
  has_many :items, foreign_key: "seller_id"
  has_many :buyed_items, foreign_key: "buyer_id", class_name: "Item" #userが買った商品
  has_many :selling_items, -> { where("buyer_id is NULL")}, foreign_key: "seller_id", class_name: "Item" #現在売っている商品
  has_many :sold_items, -> { where("buyer_id is not NULL") }, foreign_key: "seller_id", class_name: "Item" #userが既に売った商品
  has_one :profile, dependent: :destroy
  has_one :address, dependent: :destroy
  accepts_nested_attributes_for :profile
  
  has_one :payment_card, dependent: :destroy


  def self.from_omniauth(auth)
    sns = SnsCredential.where(provider: auth.provider, uid: auth.uid).first_or_create
    user = sns.user || User.where(email: auth.info.email).first_or_initialize(
      name: auth.info.name,
      email: auth.info.email
    )
    if user.persisted?
      sns.user = user
      sns.save
    end
    {user: user, sns: sns}
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def google_oauth2
    authorization
  end

  
  private

  def authorization
    sns_info = User.from_omniauth(request.env["omniauth.auth"])
    @user = sns_info[:user]
    @user.build_profile

    if @user.persisted?
      flash[:notice] = I18n.t 'devise.omniauth_callbacks.success', kind: 'Google'
      sign_in_and_redirect @user, event: :authentication
    else
      flash[:notice] = I18n.t 'devise.omniauth_callbacks.success', kind: 'Google'
      @sns_id = sns_info[:sns].id
      render 'devise/registrations/new'
    end
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  layout 'no_flash'

  def new
    @user = User.new
    @user.build_profile
  end

  def create
    if params[:sns_auth] == 'true'
      pass = Devise.friendly_token
      params[:user][:password] = pass
      params[:user][:password_confirmation] = pass
    end
    @user = User.new(user_params)
    unless @user.valid?
      flash.now[:alert] = @user.errors.full_messages
      render :new and return
    end
    session["devise.regist_data"] = {user: @user.attributes}
    session["devise.regist_data"][:user]["password"] = params[:user][:password]
    session["profile_data"] = params[:user][:profile_attributes]
    @address = @user.build_address
    render :new_address
  end

  def new_address
  end

  def create_address
    @user = User.new(session["devise.regist_data"]["user"])
    @profile = @user.build_profile(session["profile_data"])
    @address = Address.new(address_params)
    unless @address.valid?
      flash.now[:alert] = @address.errors.full_messages
      render :new_address and return
    end
    @user.build_address(@address.attributes)
    @user.save
    @profile.save
    session["devise.regist_data"]["user"].clear
    session["profile_data"].clear
    sign_in(:user, @user)
  end

  protected
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, profile_attributes:[:last_name, :first_name, :last_name_kana, :first_name_kana, :birthday])
  end

  def address_params
    params.require(:address).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :post_number, :prefecture_id, :city, :house_number, :building_name, :phone_number)
  end

  def after_update_path_for(resource)
    flash[:notice] = "変更内容を保存しました"
    edit_user_registration_path
  end

end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user, only: :show
  before_action :set_profile, only: [:edit_profile, :update_profile]
  before_action :set_address, only: [:edit_address, :update_address]
  layout 'no_flash'

  def show
  end

  def sell_items
    @sell_items = current_user.items.order("created_at DESC").page(params[:page]).per(5)
  end

  def bought_items
    @bought_items = current_user.buyed_items.page(params[:page]).per(5)
  end

  def favorite_items
    @favorite_items = Item.joins(:favorites).where(favorites: {user_id: current_user}).page(params[:page]).per(5)
  end

  def edit_profile
  end

  def update_profile
    @profile.update(profile_params)
    if @profile.save
      flash[:notice] = "変更内容が保存されました"
      redirect_to edit_profile_users_path
    else
      render :edit_profile
    end
  end

  def edit_address
  end

  def update_address
    @address.update(address_params)
    if @address.save
      flash[:notice] = "変更内容が保存されました"
      redirect_to edit_address_users_path
    else
      render :edit_address
    end
  end

  private

  def authenticate_user
    unless user_signed_in? && current_user == User.find(params[:id])
      redirect_to root_path
    end
  end

  def set_profile
    @profile = current_user.profile
  end

  def profile_params
    params.require(:profile).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :birthday)
  end

  def set_address
    @address = current_user.address
  end

  def address_params
    params.require(:address).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :post_number, :prefecture_id, :city, :house_number, :building_name, :phone_number)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_side_menu.html.haml
.side_menu
  %ul.side_menu__top
    = link_to user_path(current_user) do
      %li.selected#mypage
        %p マイページ
        %span ＞
    = link_to new_item_path do
      %li#sell_items_link
        %p 出品する
        %span ＞
    = link_to sell_items_users_path do
      %li#sold_items
        %p 出品した商品 
        %span ＞
    = link_to bought_items_users_path do
      %li#bought_items
        %p 購入した商品
        %span ＞
    = link_to favorite_items_users_path do
      %li{id: "favorite_items"}
        %p いいね!した商品
        %span ＞
  %h3 設定
  %ul.side_menu__bottom
    = link_to edit_address_users_path do
      %li#edit_address
        %p 発送元・お届け先住所変更
        %span ＞ 
    = link_to payment_cards_path do
      %li#payment_method
        %p 支払い方法
        %span ＞
    = link_to edit_user_registration_path do
      %li#edit_user
        %p メール/パスワード
        %span ＞
    = link_to edit_profile_users_path do
      %li#edit_profile
        %p 本人情報
        %span ＞
    = link_to destroy_user_session_path, method: :delete do
      %li
        %p ログアウト
        %span ＞

app/views/users/bought_items.html.haml
= render "layouts/header"
.second-header
  - breadcrumb :bought_items
  = render "layouts/breadcrumbs"
.mypage
  = render "side_menu"
  .main_contents
    .item_window
      %h3 購入した商品一覧
      .item_window__list
        - @bought_items.each do |bought_item|      
          .item           
            .item_iamge
              = link_to item_path(bought_item.id) do 
                = image_tag bought_item.item_images.first.src.url
            .p
              = "商品名: " + bought_item.name
              %br/
              = "価格: #{bought_item.price}円"
              %br/
              = "購入日: #{bought_item.updated_at.strftime("%Y年%m月%d日")}"
            .sold_out
              購入済み
     
      = paginate(@bought_items)
= render "layouts/footer"

app/views/users/edit_address.html.haml
= render "layouts/header"
.second-header
  - breadcrumb :edit_address
  = render "layouts/breadcrumbs"
= render "layouts/notifications"

.mypage
  = render "side_menu"
  .main_contents
    .sign-up
      .sign-up__top.sign-up__top--mypage
        発送元・お届け先住所
      .sign-up__bottom
        = form_with(model: @address, url: update_address_users_path, local: true) do |f|
          = render "devise/shared/error_messages", resource: @address
          .field
            %label お名前
            %span 必須
            %br/
            = f.text_field :last_name, placeholder: "例）山田"
            %br/
            = f.text_field :first_name, placeholder: "例）彩"
          .field
            %label お名前カナ
            %span 必須
            %br/
            = f.text_field :last_name_kana, placeholder: "例）ヤマダ"
            %br/
            = f.text_field :first_name_kana, placeholder: "例）アヤ"
          .field
            %label 郵便番号
            %span 必須
            %br/
            = f.text_field :post_number, placeholder: "例）123-4567"
          .field
            %label 都道府県
            %span 必須
            %br/
            = f.collection_select :prefecture_id, Prefecture.all, :id, :name, { include_blank: "選択して下さい"}
          .field
            %label 市町村
            %span 必須
            %br/
            = f.text_field :city, placeholder: "例）横浜市緑区"
          .field
            %label 番地
            %span 必須
            %br/
            = f.text_field :house_number, placeholder: "例）青山1-1-1"
          .field.field--optional
            %label 建物名
            %span 任意
            %br/
            = f.text_field :building_name, placeholder: "例）柳ビル103"
          .field.field--optional
            %label 電話番号 (ハイフンなし)
            %span 任意
            %br/
            = f.text_field :phone_number, placeholder: "例）09012345678"
          = f.submit "変更する", class: "send_btn"


= render "layouts/footer"

app/views/users/edit_profile.html.haml
= render "layouts/header"
.second-header
  - breadcrumb :edit_profile
  = render "layouts/breadcrumbs"
= render "layouts/notifications"

.mypage
  = render "side_menu"
  .main_contents
    .sign-up
      .sign-up__top.sign-up__top--mypage
        本人情報
      .sign-up__bottom
        = form_with(model: @profile, url: update_profile_users_path, local: true) do |f|
          = render "devise/shared/error_messages", resource: @profile
          .field
            %label お名前(全角)
            %span 必須
            %br/
            .two_rows_input
              = f.text_field :last_name, placeholder: "例）山田"
              = f.text_field :first_name, placeholder: "例）彩"
          .field
            %label お名前カナ(全角)
            %span 必須
            %br/
            .two_rows_input
              = f.text_field :last_name_kana, placeholder: "例）ヤマダ"
              = f.text_field :first_name_kana, placeholder: "例）アヤ"
          .field.field--birthday
            %label 生年月日
            %span 必須
            %br/
            .birthday_input
              = raw sprintf(f.date_select(:birthday, use_month_numbers: true, start_year: 1900, end_year: Time.now.year, date_separator: '%s'), '年', '月') + '日'

          = f.submit "変更する", class:"send_btn"

= render "layouts/footer"

app/views/users/favorite_items.html.haml
= render "layouts/header"
.second-header
  - breadcrumb :favorite_items
  = render "layouts/breadcrumbs"
.mypage
  = render "side_menu"
  .main_contents
    .item_window
      %h3 いいね! した商品一覧
      .item_window__list
        - @favorite_items.each do |favorite_item|      
          .item           
            .item_iamge
              = link_to item_path(favorite_item.id) do 
                = image_tag favorite_item.item_images.first.src.url
            .p
              = "商品名: " + favorite_item.name
              %br/
              = "価格: #{favorite_item.price}円"
            - if favorite_item.buyer_id != current_user.id && favorite_item.buyer_id.presence  
              .sold_out
                SOLD_OUT!
            - if favorite_item.buyer_id == current_user.id
              .sold_out
                購入済み
      = paginate(@favorite_items)
= render "layouts/footer"

app/views/users/sell_items.html.haml
= render "layouts/header"
.second-header
  - breadcrumb :sell_items
  = render "layouts/breadcrumbs"
.mypage
  = render "side_menu"
  .main_contents
    .item_window
      %h3 出品した商品一覧
      .item_window__list
        - @sell_items.each do |sell_item|      
          .item           
            .item_iamge
              = link_to item_path(sell_item.id) do 
                = image_tag sell_item.item_images.first.src.url
            .p
              = "商品名: " + sell_item.name
              %br/
              = "出品日: #{sell_item.created_at.strftime("%Y年%m月%d日")}"
            - if sell_item.buyer_id.present? 
              .sold_out
                SOLD_OUT!
      = paginate(@sell_items)

= render "layouts/footer"

app/views/users/show.html.haml
= render "layouts/header"
.second-header
  - breadcrumb :mypage
  = render "layouts/breadcrumbs"

.mypage
  = render "side_menu"
  .main_contents
    .user_header
      .user_header__info
        = image_tag asset_path("material/icon/member_photo_noimage_thumb.png")
        %p= current_user.name
        %p
          = "出品数: #{current_user.items.count}"
    .item_window
      %h3 お知らせ
      .item_window__list
        .item
          = image_tag asset_path("logo.png")
          %p たった１分！簡単出品のFURIMAへようこそ!!        
        .item
          = link_to "一覧を見る", "#", class: "index_btn"


= render "layouts/footer"