config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: "users/registrations"
  }
  devise_scope :user do
    get'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
    get '/users/sign_out', to: 'devise/sessions#destroy'
  end
  

  resources :users, only: :show do
    collection do
      get 'edit_profile', 'edit_address'
      get 'sell_items'
      get 'bought_items'
      patch 'update_profile', 'update_address'
      get 'favorite_items'
    end
  end
 
  root 'items#index'

  resources :payment_cards, only: [:new, :create, :index, :destroy]
  resources :items do
    resources :favorites, only: [:create, :destroy]
    collection do
      get 'search'
    end
    resources :purchases do
      collection do
        get :buy
        post :pay
      end
    end
  end
  resources :categories, only: [:index, :show] do
    collection do
      get "children_category"
      get "grandchildren_category"
    end
  end
end

app/models/item.rb
class Item < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :prefecture
  belongs_to :category
  belongs_to :seller, class_name: 'User'
  belongs_to :buyer, class_name: 'User', optional: :true
  has_many :favorites, dependent: :destroy
  has_many :item_images, dependent: :destroy
  accepts_nested_attributes_for :item_images, allow_destroy: true
  validates :name, :text, :item_images, :price, :status, :delivery_charge_bearer, :prefecture_id, :delivery_days, presence: true
  enum delivery_days: {"1日〜2日で発送":1, "2日〜3日で発送": 2, "3日〜4日で発送": 3, "4日〜7日で発送":4 }, _prefix: true
  enum delivery_charge_bearer: {"送料込み（出品者負担）":1, "着払い（購入者負担）":2} ,_prefix: true
  enum status: {"新品、未使用":1, "未使用に近い":2, "目立った傷や汚れなし":3, "やや傷や汚れあり":4, "傷や汚れあり":5, "全体的に状態が悪い":6} ,_prefix: true

  def previous
    Item.where("id < ?", self.id).where(buyer_id: nil).order("id DESC").first
  end
  
  def next
    Item.where("id > ?", self.id).where(buyer_id: nil).order("id ASC").first
  end

  def self.search(search)
    return Item.all unless search
    Item.where('name LIKE(?)', "%#{search}%")
  end


end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :move_to_root_path, except: [:index, :show, :search], unless: :user_signed_in?
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user, only: [:edit, :update, :destroy]

  def index
    @items = Item.where(buyer_id: nil).order("created_at DESC").page(params[:page]).per(9)
    
  end

  def search
    @items = Item.search(params[:keyword]).where(buyer_id: nil).order("created_at DESC").page(params[:page]).per(9)
  end

  def show
    @main_image = @item.item_images.first
    @grandchild_category = @item.category
    @child_category = @grandchild_category.parent
    @parent_category = @child_category.parent
    @favorite = Favorite.new
  end

  def new 
    @item = Item.new
    @item.item_images.new
    @parents = Category.where(ancestry: nil)
  end


  def create
    begin
      @item = Item.new(item_params)
      if @item.save
          redirect_to root_path, notice: "出品が完了しました"
        else
          redirect_to new_item_path, alert: "必須項目を入力して下さい"
        end
    rescue => e
      puts "エラーが発生しました"
      Rails.logger.debug e.message
      redirect_to root_path
    end
  end

  def edit
    @grandchild = @item.category
    @child = @grandchild.parent
    @parent = @child.parent
    @grandchildren = @child.children
    @children = @parent.children
    @parents = Category.where(ancestry: nil)
  end

  def update
    if @item.update(item_params)
      redirect_to item_path(@item), notice: "変更内容を保存しました"
    else
      redirect_to edit_item_path(@item), alert: "必須項目を入力して下さい"
    end
  end

  def destroy
    if @item.destroy
      flash[:notice] = "削除が完了しました"
      redirect_to root_path
    else
      flash[:alert] = "削除できませんでした"
      render :show
    end
  end

  private
  def item_params
    params.require(:item).permit(:name, :text, :category_id, :brand, :status, :delivery_charge_bearer, :prefecture_id, :delivery_days, :price, [item_images_attributes: [:src, :_destroy, :id]]).merge(seller_id: current_user.id)
  end

  def set_item
    @item = Item.find(params[:id])
  end

  def move_to_root_path
    redirect_to root_path 
    flash[:alert] = "出品するには新規登録、ログインが必要です"
  end

  def authenticate_user
    if Item.find(params[:id]).seller != current_user
      redirect_to root_path
    end
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_app_introduction.html.haml
.theme-visual
  .content
    .content__title
      人生を変えるフリマアプリ
    .content__text
      %p FURIMAは 誰でも簡単に出品・購入できる
      %p フリマアプリです"
    .content__dl-badge
      = link_to image_tag('google-play-badge.png', alt: 'google badge', height: '55', width: 'auto', class: ''), "#"
      = link_to image_tag('Download_on_the_App_Store_Badge_US-UK_RGB_blk_092917.png', alt: 'apple badge', height: '54', width: 'auto', class: ''), "#"

.introduction
  .title
    FURIMAが選ばれる3つの理由
    .title__border
  %ul.lists
    %li.list
      .list__image
        .number
          1
        = image_tag 'pict/pict-reason-01.jpg', class: 'image'
      .list__subtitle
        %span 3分
        ですぐに出品
      %p.list__text
        スマホで入力するだけで簡単に出品できる！
    %li.list
      .list__image
        .number
          2
        = image_tag 'pict/pict-reason-02.jpg', class: 'image'
      .list__subtitle
        %span シンプル
        で使いやすい
      %p.list__text
        めんどくさい入力は必要なく、検索も購入もスムーズ！
    %li.list
      .list__image
        .number
          3
        = image_tag 'pict/pict-reason-03.jpg', class: 'image'
      .list__subtitle
        手数料
        %span 業界最安値
      %p.list__text--center
        最大3%でお得に出品&購入！

.dl-content
  .dl-content__title
    会員数日本一位
  .dl-content__text
    %p FURIMAは、フリマアプリで最も人気。
    %p 出品・購入回数も業界最多です！
    %p ほしかったあの商品に出会えるかもしれません。
  .dl-content__dl-badge
    = link_to image_tag('google-play-badge.png', alt: 'google badge', height: '55', width: 'auto', class: ''), "#"
    = link_to image_tag('Download_on_the_App_Store_Badge_US-UK_RGB_blk_092917.png', alt: 'apple badge', height: '54', width: 'auto', class: ''), "#"
  
.service-feature
  .title
    FURIMAの特徴
    .title__border
  %ul.lists
    %li.list
      .list__image
        = image_tag 'icon/icon-01.png', class: 'image'
      .list__subtitle
        簡単に売り買いできる
      %p.list__text
        スマホひとつで、いつでもどこでも簡単に出品・購入が可能！
    %li.list
      .list__image
        = image_tag 'icon/icon-03.png', class: 'image'
      .list__subtitle
        売上金は即日振込みに対応
      %p.list__text
        午前9時までに振込を依頼いただければ、翌日に指定の口座に入金いたします!
    %li.list
      .list__image
        = image_tag 'icon/icon-04.png', class: 'image'
      .list__subtitle
        様々な支払いに対応
      %p.list__text--center
        お支払いは、クレジットカードだけでなく、ポイントや売上金など多彩な方法があります。

app/views/items/_item.html.haml
- items.each do |item|
  %li.list
    = link_to item_path(item.id) do
      = image_tag item.item_images.first.src_url, class: 'image'
      .info
        .info__top
          .name
            = item.name
          .price
            = "#{item.price}円 "
            %p (税込)
        .favorite_count
          = image_tag "icon/icon_stared", size: "18x18"
          = item.favorites.count
          
      

app/views/items/buy.html.haml
= render "devise/template/header"
.wrapper
  .confirm-item
    .confirm-item__box

      %section.confirm-item__box__title
        購入内容の確認

      %section.confirm-item__box__itemView
        .confirm-item__box__itemView__image
          =image_tag "pict-reason-02.jpg", size:"85x85"
        .confirm-item__box__itemView__text
          使い勝手抜群の最新バージョンです。<br>
          状態も綺麗なのでおすすめです！
          .confirm-item__box__itemView__text__price
            ¥9,980(税込み)送料込み

      %section.confirm-item__box__payMent
        .confirm-item__box__payMent__text
          支払い金額
        .confirm-item__box__payMent__price
          ¥9,980

      %section.confirm-item__box__payMethod
        .confirm-item__box__payMethod__text
          支払い方法 :クレジットカード
          .confirm-item__box__payMethod__info
            %p.creditNumber
              カード番号: ********1234 
            %p.expirDate
              有効期限: 24年12月
        .confirm-item__box__payMethod__info__edit
          %p.creditChange
            変更する
          %p.creditRegistration
            登録する

      %section.confirm-item__box__address
        .confirm-item__box__address__text
          配送先
          .confirm-item__box__address__info
            %p.postNumber
              〒550-0012
            %p.streetAddress
              大阪府大阪市西区東町1-10-11
            %p.userName
              本多 淳
        .confirm-item__box__address__change
          変更する

      %section.confirm-item__box__purchase
        %input{type:"submit",class:"purchase-btn", value:"購入内容を確定する"}
= render "devise/template/footer"

app/views/items/edit.html.haml
= render "devise/template/header"
.wrapper
  .form-new
    = form_with model: @item, local: true do |f|
      .form-image
        .form-image__label
          %label<>出品画像
          %span<>必須
        %p 最大5枚までアップロードできます
        .form-image__box
          .prev-content
            - @item.item_images.each_with_index do |image, i|
              .preview-box{data:{preview_id: i}}
                .upper-box
                  = image_tag image.src.url, alt: "preview"
                .lower-box
                  .delete-box{data:{delete_id: i}}
                    %span 削除

          .label-content
            = f.label :"item_images_attributes_#{@item.item_images.length}_src", class: "label-box" do
              %pre.label-box-visible 
                = image_tag "icon_camera.png", size: '35x35' 
          .hidden-content
            = f.fields_for :item_images do |i|
              = i.file_field :src, class: "hidden-field"
              = i.check_box:_destroy, class: "hidden-checkbox"
            - @item.item_images.length.upto(@item.item_images.length + 4) do |i|
              %input{name: "item[item_images_attributes][#{i}][src]", id: "item_item_images_attributes_#{i}_src", class:"hidden-field new-image", type:"file"}


      .form-item
        .form-item__name
          .form-item__name__label
            %label<>商品名
            %span<>必須
          .form-item__name__input
            = f.text_field :name, placeholder: "40文字まで"
        .form-item__text
          .form-item__text__label
            %label<>商品の説明
            %span<>必須
          .form-item__text__input
            = f.text_area :text, placeholder: "商品の説明（必須1,000文字以内(色、素材、重さ、定価、注意点など）例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。"

      .form-detail
        %p 商品の詳細
        .form-detail__category
          .form-detail__category__label
            %label<>カテゴリー
            %span<>必須
          .form-detail__category__input
            = f.collection_select :category_id, @parents, :id, :name, {selected: @parent.id}, {class: "select-default", id: "category_select"}
            = f.collection_select :category_id, @children, :id, :name, {selected: @child.id}, {class: "select-default", id: "children_categories"}
            = f.collection_select :category_id, @grandchildren, :id, :name, {selected: @grandchild.id}, {class: "select-default", id: "grandchildren_categories"}

        .form-detail__brand
          .form-detail__brand__label
            %label<>ブランド
            %span<>任意
          .form-detail__brand__input
            = f.text_field :brand, placeholder: "例）シャネル"
        .form-detail__status
          .form-detail__status__label
            %label<>商品の状態
            %span<>必須
          .form-detail__status__input
            = f.select :status, Item.statuses.keys.map{|k| [k]}, {include_blank: "選択して下さい"}
      .form-shipping
        .form-shipping__title
          %p 配送について
        .form-shipping__charge
          .form-shipping__charge__label
            %label<>配送料の負担
            %span<>必須
          .form-shipping__charge__input
            = f.select :delivery_charge_bearer, Item.delivery_charge_bearers.keys.map{|k| [k]}, {include_blank: "選択して下さい"}
          
        .form-shipping__area
          .form-shipping__area__label
            %label<>発送元の地域
            %span<>必須
          .form-shipping__area__input
            = f.collection_select :shipping_area,  Prefecture.all, :id, :name, {include_blank: "選択して下さい"}
        .form-shipping__days
          .form-shipping__days__label
            %label<>発送までの日数
            %span<>必須
          .form-shipping__days__input
            = f.select :delivery_days, Item.delivery_days.keys.map{|k|[k]}, {include_blank: "選択して下さい"}
      .form-price
        .form-price__title
          %p 価格（¥300~9,999,999
        .form-price__value
          .form-price__value__left
            %label<>販売価格
            %span<>必須
          .form-price__value__right
            %span<>¥
            = f.text_field :price, placeholder: "0"
        .form-price__fee
          販売手数料（10%）
          %span<>ー
        .form-price__plofit
          販売利益
          %span<>ー
      .form-btn
        .form-btn__top
          = f.submit '変更する', class:"form-btn__top"
        .form-btn__midle
          = link_to "#" do
            下書きに保存
        .form-btn__bottom
          = link_to root_path do
            もどる

      .form-term
        禁止されている行為および出品物を必ずご確認ください。偽ブランド品や盗品物などの販売は犯罪であり、法律により処罰される可能性があります。 また、出品をもちまして加盟店規約に同意したことになります。
  = render "devise/template/footer"

app/views/items/index.html.haml
= render "layouts/header"

.contents
  - unless user_signed_in?
    = render "app_introduction" 
  .products-container
    .products-index
      .title
        商品一覧
        .title__border
      - if @items
        %ul.lists
          = render "item", items: @items
  
      = paginate @items

= render "layouts/footer"

app/views/items/new.html.haml
= render "devise/template/header"
.wrapper
  .form-new
    = form_with model: @item, local: true do |f|
      .form-image
        .form-image__label
          %label<>出品画像
          %span<>必須
        %p 最大5枚までアップロードできます
        .form-image__box
          .prev-content
          .label-content
            %label{for: "item_item_images_attributes_0_src", class: "label-box"} 
              %pre.label-box-visible 
                = image_tag "icon_camera.png", size: '35x35' 
          .hidden-content
            = f.fields_for :item_images do |i|
              = i.file_field :src, class: "hidden-field new-image"
              %input{class:"hidden-field new-image", type: "file", name: "item[item_images_attributes][1][src]", id: "item_item_images_attributes_1_src" }
              %input{class:"hidden-field new-image", type: "file", name: "item[item_images_attributes][2][src]", id: "item_item_images_attributes_2_src" }
              %input{class:"hidden-field new-image", type: "file", name: "item[item_images_attributes][3][src]", id: "item_item_images_attributes_3_src" }
              %input{class:"hidden-field new-image", type: "file", name: "item[item_images_attributes][4][src]", id: "item_item_images_attributes_4_src" }


      .form-item
        .form-item__name
          .form-item__name__label
            %label<>商品名
            %span<>必須
          .form-item__name__input
            = f.text_field :name, placeholder: "40文字まで"
        .form-item__text
          .form-item__text__label
            %label<>商品の説明
            %span<>必須
          .form-item__text__input
            = f.text_area :text, placeholder: "商品の説明（必須1,000文字以内(色、素材、重さ、定価、注意点など）例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。"

      .form-detail
        %p 商品の詳細
        .form-detail__category
          .form-detail__category__label
            %label<>カテゴリー
            %span<>必須
          .form-detail__category__input
            = f.collection_select :category_id, @parents, :id, :name, {prompt: "選択して下さい"}, {class: "select-default", id: "category_select"}
            
        .form-detail__brand
          .form-detail__brand__label
            %label<>ブランド
            %span<>任意
          .form-detail__brand__input
            = f.text_field :brand, placeholder: "例）シャネル"
        .form-detail__status
          .form-detail__status__label
            %label<>商品の状態
            %span<>必須
          .form-detail__status__input
            = f.select :status, Item.statuses.keys.map{|k| [k]}, {include_blank: "選択して下さい"}
      .form-shipping
        .form-shipping__title
          %p 配送について
        .form-shipping__charge
          .form-shipping__charge__label
            %label<>配送料の負担
            %span<>必須
          .form-shipping__charge__input
            = f.select :delivery_charge_bearer, Item.delivery_charge_bearers.keys.map{|k| [k]}, {include_blank: "選択して下さい"}
          
        .form-shipping__area
          .form-shipping__area__label
            %label<>発送元の地域
            %span<>必須
          .form-shipping__area__input
            = f.collection_select :prefecture_id,  Prefecture.all, :id, :name, {include_blank: "選択して下さい"}
        .form-shipping__days
          .form-shipping__days__label
            %label<>発送までの日数
            %span<>必須
          .form-shipping__days__input
            = f.select :delivery_days, Item.delivery_days.keys.map{|k|[k]}, {include_blank: "選択して下さい"}
      .form-price
        .form-price__title
          %p 価格（¥300~9,999,999
        .form-price__value
          .form-price__value__left
            %label<>販売価格
            %span<>必須
          .form-price__value__right
            %span<>¥
            = f.text_field :price, placeholder: "0"
        .form-price__fee
          販売手数料（10%）
          %span<>ー
        .form-price__plofit
          販売利益
          %span<>ー
      .form-btn
        .form-btn__top
          = f.submit '出品する', class:"form-btn__top"
        .form-btn__midle
          = link_to "#" do
            下書きに保存
        .form-btn__bottom
          = link_to root_path do
            もどる

      .form-term
        禁止されている行為および出品物を必ずご確認ください。偽ブランド品や盗品物などの販売は犯罪であり、法律により処罰される可能性があります。 また、出品をもちまして加盟店規約に同意したことになります。
  = render "devise/template/footer"

app/views/items/search.html.haml
= render "layouts/header"

.contents
  
    
  .products-container
    .products-index
      .title
        商品一覧
        .title__border
      - if @items
        %ul.lists
          = render "item", items: @items
  
      = paginate @items

= render "layouts/footer"

app/views/items/show.html.haml
= render "layouts/header"

.wrapper
  .item-box
    .item
      %h2.item__name
        = @item.name
        - if user_signed_in?
          - if @item.buyer_id != current_user.id && @item.buyer_id.presence  
            .sold_out
              SOLD_OUT!
          - if @item.buyer_id == current_user.id
            .sold_out
              購入済み
      %ul.item__images
        %li.item__images__main
          = image_tag @main_image.src.url, size: "400x400"
 
        %ul.item__images__sub
          - @item.item_images.each do |image|
            %li
              = image_tag image.src.url, size:"100x100"     

      - if user_signed_in? 
        - unless  current_user.id == @item.seller_id
          = render 'favorites/favorite'
        

      .item__price
        = "#{@item.price}円"
        .item__price__info
          %span
            = @item.delivery_charge_bearer
      .item__details
        %p
          = @item.text
      %table.item__table
        %tbody.item__info
          %tr
            %th 出品者
            %td
              = @item.seller.name
          %tr
            %th カテゴリ
            %td
              = link_to @parent_category.name, category_path(@parent_category)
              = link_to @child_category.name, category_path(@child_category)
              = link_to @grandchild_category.name, category_path(@grandchild_category)
          %tr
            %th ブランド
            %td
              = @item.brand
          %tr
            %th 商品の状態
            %td
              = @item.status
          %tr
            %th 配送料の負担
            %td
              = @item.delivery_charge_bearer
          %tr
            %th 発送元の地域
            %td
              = @item.prefecture.name
          %tr
            %th 発送日の目安
            %td
              = @item.delivery_days

      -# セラーとカレントユーザーが同じ場合下記表示/
      - unless @item.buyer_id.present?
        - if user_signed_in? && current_user.id == @item.seller_id
          %ul.item__edit-btns
            %li.edit-btn
              = link_to edit_item_path(@item.id) do
                編集
            %li.delete-btn
              = link_to item_path(@item.id), method: :delete do
                削除
        - elsif user_signed_in?
          .item__buy-btn
            = link_to buy_item_purchases_path(@item.id) do
              購入画面に進む

    %ul.pagenation
      - if request.referer&.include?("/users/sell_items")  or request.referer&.include?("/users/bought_items") or request.referer&.include?("/users/favorite_items")
        = link_to "<< 戻る", :back
      -else
        %li.prep-item
          - if @item.previous.present?
            = link_to item_path(@item.previous) do
              << 前へ
        %li.prep-item
          - if @item.next.present?
            = link_to item_path(@item.next) do
              次へ >>
= render "layouts/footer"