config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: "users/registrations"
  }
  devise_scope :user do
    get'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
    get '/users/sign_out', to: 'devise/sessions#destroy'
  end
  

  resources :users, only: :show do
    collection do
      get 'edit_profile', 'edit_address'
      get 'sell_items'
      get 'bought_items'
      patch 'update_profile', 'update_address'
      get 'favorite_items'
    end
  end
 
  root 'items#index'

  resources :payment_cards, only: [:new, :create, :index, :destroy]
  resources :items do
    resources :favorites, only: [:create, :destroy]
    collection do
      get 'search'
    end
    resources :purchases do
      collection do
        get :buy
        post :pay
      end
    end
  end
  resources :categories, only: [:index, :show] do
    collection do
      get "children_category"
      get "grandchildren_category"
    end
  end
end

app/views/layouts/_breadcrumbs.html.haml
.breadcrumbs
  = breadcrumbs separator: " &rsaquo; ", class: "breadcrumbs-list"

app/views/layouts/_footer.html.haml
.footer
  .footer-banner
    .footer-banner__inner
      %h2.footer-banner__inner--title
        だれでもかんたん、人生を変えるフリマアプリ
      %p.footer-banner__inner--text
        今すぐ無料ダウンロード！
      .footer-bannaer__inner--icon
        = link_to root_path do
          = image_tag 'Download_on_the_App_Store_Badge_US-UK_RGB_blk_092917.png', size: "180x53"
        = link_to root_path do
          = image_tag 'google-play-badge.png', size: "180x55"

  .footer-footer
    %ul.footer-footer__contents    
      %li.footer-footer__contents--content
        %h2.footer-footer__contents--content--head
          FURIMAについて
        %ul
          %li
            = link_to '会社概要(運営会社)', root_path 
          %li
            = link_to 'プライバシーポリシー', root_path 
          %li
            = link_to 'FURIMA利用規約', root_path
          %li
            = link_to 'ポイントに関する特約', root_path  
      %li.footer-footer__contents--content
        %h2.footer-footer__contents--content--head
          FURIMAを見る
        %ul
          %li
            = link_to 'カテゴリー一覧', root_path 
          %li
            = link_to 'ブランド一覧', root_path          
      %li.footer-footer__contents--content
        %h2.footer-footer__contents--content--head
          ヘルプ＆ガイド
        %ul
          %li
            = link_to 'FURMIMAガイド', root_path 
          %li
            = link_to 'FURIMAロゴ利用ガイドライン', root_path 
          %li
            = link_to 'お知らせ', root_path 

    .footer-footer__logo
      = link_to root_path do
        = image_tag 'logo-white.png',size: "160x46"
      %p.footer-footer__logo--text
        ©︎FURIMA
= link_to new_item_path, class: "exhibition-btn" do
  .exhibition-btn__text
    出品する
  = image_tag "icon_camera.png", size: "55x55"

app/views/layouts/_header.html.haml
.header
  .topHeader
    .topHeader__main
      %h1.topHeader__main--logo
        = link_to root_path do
          = image_tag 'logo.png', size: '140x40' 
      .search-form
        = form_with(url: search_items_path, local: true, method: :get,  class: "search-box") do |f|
          = f.text_field :keyword, placeholder: "商品を検索する", class: "search-box__text"
          = button_tag type: "submit",  class: "search-box__btn" do
            = image_tag 'icon-search.png', size: '19x19'
    .nav-bar 
      %ul.nav-bar__left
        %li.nav-bar__left__left
          = link_to 'カテゴリーから探す', categories_path, id: "category-search"
          .category-menu
            .category-list.parents-list
              -@parents.each do |parent|
                = link_to "#{parent.name}", category_path(parent), class: "category parent_category", id: "#{parent.id}"
            .category-list.children-list
            .category-list.grandchildren-list
        %li.nav-bar__left__right
          = link_to 'ブランド', root_path
          
      %ul.nav-bar__right
        - if user_signed_in?
          %li.nav-bar__right
            = link_to "マイページ", user_path(current_user)
        - else
          %li.nav-bar__right_login
            = link_to 'ログイン', user_session_path
          %li.nav-bar__right__new
            = link_to '新規会員登録', new_user_registration_path

app/views/layouts/_notifications.html.haml
.notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title FURIMA
    %script{src: "https://js.pay.jp/", type: "text/javascript"}
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
  %body
    
    = render 'layouts/notifications'
    = yield

app/views/layouts/no_flash.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title FURIMA
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield